
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int TIMES = 5;
  public static final int PLUS = 3;
  public static final int KW_IF = 13;
  public static final int RBRACE = 10;
  public static final int RPAREN = 12;
  public static final int SEMI = 2;
  public static final int IDENTIFIER = 17;
  public static final int LPAREN = 11;
  public static final int LBRACE = 9;
  public static final int NUMBER = 18;
  public static final int EOF = 0;
  public static final int KW_WHILE = 15;
  public static final int DIV = 6;
  public static final int MINUS = 4;
  public static final int KW_RETURN = 16;
  public static final int error = 1;
  public static final int EQ = 7;
  public static final int NEQ = 8;
  public static final int KW_ELSE = 14;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "SEMI",
  "PLUS",
  "MINUS",
  "TIMES",
  "DIV",
  "EQ",
  "NEQ",
  "LBRACE",
  "RBRACE",
  "LPAREN",
  "RPAREN",
  "KW_IF",
  "KW_ELSE",
  "KW_WHILE",
  "KW_RETURN",
  "IDENTIFIER",
  "NUMBER"
  };
}

